#######################################################
## @author   Md. Mushfiq Fuad                        ##
## @version  1.0                                     ##
## @since    11 Apr, 2022                            ##
#######################################################

databaseChangeLog:
  - changeSet:
      id: create application_tour_instructions table
      author: lnm-service Md. Mushfiq Fuad
      changes:
        - createTable:
            tableName: application_tour_instructions
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: user_id
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: is_tour_active
                  type: BOOLEAN
                  constraints:
                    nullable: false
                  defaultValue: 0
              - column:
                  name: remarks
                  type: LONGTEXT
                  constraints:
                    nullable: true
              - column:
                  name: created_at
                  type: timestamp
                  constraints:
                    nullable: false
              - column:
                  name: updated_at
                  type: timestamp
                  constraints:
                    nullable: false
              - column:
                  name: created_by
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: updated_by
                  type: BIGINT
                  constraints:
                    nullable: false
