#######################################################
## @author   Md. Mushfiq Fuad                        ##
## @version  1.0                                     ##
## @since    23 Jan, 2022                            ##
#######################################################

databaseChangeLog:
  - changeSet:
      id: create noc_application_process_logs
      author: lnm-service Md. Mushfiq Fuad
      changes:
        - createTable:
            tableName: noc_application_process_logs
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: noc_application_id
                  type: BIGINT
                  constraints:
                    nullable: false
                    foreignKeyName: fk_noc_application_process_logs_noc_application_id
                    references: noc_applications(id)
              - column:
                  name: noc_lab_tests_id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    nullable: false
              - column:
                  name: test_issue_date
                  type: timestamp
                  constraints:
                    nullable: true
              - column:
                  name: test_response_date
                  type: timestamp
                  constraints:
                    nullable: true
              - column:
                  name: test_status
                  type: varchar(100)
                  constraints:
                    nullable: true
              - column:
                  name: created_at
                  type: timestamp
                  constraints:
                    nullable: false
              - column:
                  name: updated_at
                  type: timestamp
                  constraints:
                    nullable: false
              - column:
                  name: created_by
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: updated_by
                  type: BIGINT
                  constraints:
                    nullable: false
