#######################################################
## @author   Md. Emran Hossain                       ##
## @version  1.0                                     ##
## @since    20 Jan, 2022                            ##
#######################################################

spring:
  datasource:
    url: jdbc:postgresql://172.16.28.131:5432/lnm-service?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    dbcp2:
      initial-size: 10
      max-total: 380
      min-idle: 2
      max-idle: 40

  liquibase:
    change-log: classpath:/db.changelog/db.changelog-master-dev.yml
    drop-first: true
    enabled: true

  jpa:
    properties:
      hibernate:
        generate-statistics: false
  data:
    rest:
      max-page-size: 10000
  hateoas:
    use-hal-as-default-json-media-type: false

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: ERROR
    com:
      synesisit:
        lnm: info
  file:
    name: /var/log/lnm-service/app.log
    max-size: 10MB
    max-history: 0
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
    
acl:
  url: http://172.16.28.131:8201
endpoint:
  userdetails: /api/user/get-user-details-by-user-id/
  citizenuserdetails: /api/user/get-by-id/
  department: /api/department/get-by-id/